[project]
name = "tadpole"
version = "0.1.0"
description = "My interpreter"
dependencies = [
    "pandas",
    "lark",
    "lark[interegular]",
    "pydot",
    "pyparsing"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
tadpole = "tadpole.main:main"

[tool.setuptools.packages.find]
include = ["tadpole*"]