
# Project description and dependencies to be installed
[project]
name = "tadpole"
version = "0.12.1"
description = "My interpreter"
dependencies = [
    "pandas",
    "lark",
    "lark[interegular]",
    "pydot",
    "pyparsing",
    "tabulate"
]

# Optional dependencies for devs
[project.optional-dependencies]
dev = [
    "pytest"
]

# Custom script for running the interpreter
[project.scripts]
tadpole = "tadpole.main:main"

# Include tadpole as a package when installing
[tool.setuptools.packages.find]
include = ["tadpole*"] 